version: "3.8"

services:
    app:
        build: .
        container_name: resturant
        ports:
            - "3000:3000"
        volumes:
            - ./database.db:/usr/src/app/database.db
        environment:
            - NODE_ENV=production
