version: "3.8"

services:
  app:
    build: .
    container_name: resturant
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - /root/n8n-docker/app_data/database.db:/usr/src/app/database.db
    networks:
      - backend

networks:
  backend:
    driver: bridge
