name: CI/CD - Build and Push Docker Image

on:
  push:
    branches: [ "master" ]   # غيرها إلى master إذا مشروعك يستخدم master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. سحب الكود من GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. تسجيل الدخول في Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. بناء ورفع صورة Docker
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:latest
